bucket_name = "my-project-bucket-name-is-final-bucket"
location = "us-central1"
project_id = "terraform-learn-382907"
region = "us-central1"
credentails = "C:\\Users\\RASUVARN\\Downloads\\terraform-learn-382907-f703fb75e1d6.json"
