name: Terraform Deployment
on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/777252214638/locations/global/workloadIdentityPools/k8s-newpool/providers/k8s-provider'
          service_account: gcp-sa-key@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s"
        working-directory: ./Terraform-GCP-Actions
        
        
        
        
      
      
