name: GitHub Actions Workload Identity Demo
on: [push]
jobs:
  List-Buckets:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: projects/777252214638/locations/global/workloadIdentityPools/github-pool2/providers/github-provider2
          service_account: github-actions@terraform-learn-382907.iam.gserviceaccount.com

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "List buckets"
        run: "gcloud storage ls"

      - name: Terraform init    
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        working-directory: ../Terraform-GCP-Actions

      - name: Terraform apply
        run: terraform apply -auto-approve 
        working-directory: ../Terraform-GCP-Actions

